### ISSUE TITLE
README UPDATE: Linux command

### ISSUE THREAD

**Issue by ObiSandwich** [TravisHunting/ComicDownloader#10]
Suggestion to include in your Readme: Include a Linux command example, the -u and -f arguments don't work in Linux and also the command needs the proceeding ./ to work in Linux Terminal.

Linux example:
`./comicScraper.py https://readcomiconline.li/Comic/Lucifer-2016 Lucifer`

**Comment by ObiSandwich** [comment]
Scrap that! Sorry. I was using an older version of your script!

**Comment by ObiSandwich** [comment]
Before I closed this I forgot to highlight the ./ thing! 

This would be worth mentioning in the Readme for other Linux user: For Linux Terminal, the command needs the proceeding ./

Linux example:
`./comicScraper.py https://readcomiconline.li/Comic/Lucifer`

**Comment by AustinHunting** [comment]
The script makes changes to the directory you are currently in, i.e. `cd /tmp/comics/ && $HOME/ComicDownloader/comicScraper.py` will populate `/tmp/comics/` with downloaded files.

We chose this option so a user could add the script to their $PATH variable and still download comics to a selected directory. 
With that in mind we do not think adding documentation around `./` is a good idea. It prompts the user to only ever run it from the git directory. 

We can however add a note to the README.md to denote this.
