### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by ObiSandwich** [TravisHunting/ComicDownloader#13]
You guys may have a perfectly good reason not to do this, but so to avoid any confusion when you tweak and update this thing - is there any chance you could add a Version/Release number to the script please? Just so I know I'm using the latest :)

**Comment by AustinHunting** [comment]
sure, adding a versioning system is probably not a bad idea

**Comment by AustinHunting** [comment]
Pull #15 should deal with this. marking it as closed.
