### ISSUE TITLE
Custom batches?

### ISSUE THREAD

**Issue by ObiSandwich** [TravisHunting/ComicDownloader#14]
Based on the potential anti-bot protection from readcomiconline.li as mentioned here #3 that stops/skips the downloading process and my never ending quest to download the (large) complete run of...

`https://readcomiconline.li/Comic/Star-Wars-2015`

...is there a way around this by reducing large batches to smaller batches? So is there an argument/option to download a custom batch/selection of issues instead of the complete run, eg. 1 to 30?

**Comment by AustinHunting** [comment]
as of right now there is no option to download a set of issues. I've added it to the todo list and will keep this thread updated with progress.

**Comment by AustinHunting** [comment]
Please note, this project has been archived and all future updates will be posted to [team-hunting/ComicDownloader](https://github.com/team-hunting/ComicDownloader)

If you feel this issue has not been addressed to your satisfaction please open an issue or pull request in the new repository. As always we appreciate your support.
