### ISSUE TITLE
Corrupt JPG's

### ISSUE THREAD

**Issue by ObiSandwich** [TravisHunting/ComicDownloader#22]
**Tested on: Linux LMDE4 - [High Quality](https://github.com/TravisHunting/ComicDownloader/blob/highquality/comicScraper.py) branch (hi res) and regular script (low res)**

First mentioned #3 it looks like the corrupt JPG issue may not be a CAPTCHA thing (no CAPTCHA warning appeared), but an error with certain comics - always the same comics when repeated - And all corrupt JPGs visible to read on readcomiconline.li ...all very strange why it's doing this for the download only right?

Does the same thing happen on Windows?

**EXAMPLE 1**
The following downloads all comics except 17 and 16. These missing comics are downloaded as 1.6kb empty corrupt JPGs. **The same thing happens when downloading these corrupt comics as single issues.**

`./comicScraper.py https://readcomiconline.li/Comic/Darth-Vader -c`
`./comicScraper.py https://readcomiconline.li/Comic/Darth-Vader/Issue-17?id=23674`
`./comicScraper.py https://readcomiconline.li/Comic/Darth-Vader/Issue-16?id=18355`

![Screenshot from 2022-01-08 11-09-59](https://user-images.githubusercontent.com/41534480/148641898-3a70b0f2-fc63-45f3-94e3-e77221b2b007.png)

**EXAMPLE 2**
This run only includes comic 7, all others are corrupt JPGs.

`./comicScraper.py https://readcomiconline.li/Comic/The-Superior-Foes-of-Spider-Man -c`

Working comic example
`./comicScraper.py https://readcomiconline.li/Comic/The-Superior-Foes-of-Spider-Man/Issue-7?id=2109`

Corrupt comic example
`./comicScraper.py https://readcomiconline.li/Comic/The-Superior-Foes-of-Spider-Man/Issue-1?id=2083`

**EXAMPLE 3**
Corrupt JPGs: 1-13, 15-16 and Annuals 1-3.

`./comicScraper.py https://readcomiconline.li/Comic/Star-Wars-2015 -c`

Corrupt comic example
`./comicScraper.py https://readcomiconline.li/Comic/Star-Wars-2015/Issue-13?id=11925`

**Comment by TravisHunting** [comment]
My first guess is that they're not actually JPG's, can you try renaming
some of the files to .png , .gif and see if any of those work?

I'll try downloading that one later

**Comment by ObiSandwich** [comment]
Good idea, but that didn't work - tried: .png, .gif, .jpeg

When manually saving a corrupt comic direct from readcomiconline.li (Save As) the file is saved locally as .jpg

**Comment by TravisHunting** [comment]
.avif and .webp other possibilities (seems less likely)

**Comment by ObiSandwich** [comment]
I guess the problem here is the files are 1.6kb, so there can't be any data in there.

**Comment by ObiSandwich** [comment]
I think I found something - based on readcomiconline.li page sources, it looks like the corrupt JPGs HTML source is different;

Regular JPG source that I guess you identify in your script;
`src="https://2.bp.blogspot.com/vp9_q4Rl5yInGVGp3Nit_BBLy6TLr9fyryg_VcAet6F_-vpFQKv6aS6FuEpiLbM5z-c-Kvj4c7PwahvOZjuiW_JspXb64-RbPpSQ63STUXdqzLCVGCWY5yi53WUStRRaMe86hTRb7lA=s0">`
Source: https://readcomiconline.li/Comic/Darth-Vader/Issue-1?id=16932

Corrupt JPG comic source;
`src="https://2.bp.blogspot.com/-EZGMHhMjxWk/VtboGervoMI/AAAAAAAAHp8/QevaGio01xA/s0-Ic42/RCO001.jpg">`
Source: https://readcomiconline.li/Comic/Darth-Vader/Issue-17?id=23674

Tested this on my previous examples and they are the same - therefore corrupt sources end in a .jpg extension. The corrupt source looks more like traditional web design source to me, so I guess the regular source that you use is parsing through a backend database?? 

Any way I hope this gives you a clue about why there's a difference between the two sources.

**Comment by AustinHunting** [comment]
Catching all the images is going to be the biggest issue going forward, there's no promise the readcomiconline.li will always use the same format for hosting images. 

Anyway, we could probably add a size check for downloaded images to flag if a comic _might_ be corrupt and add a loop that hunts for links in the format you've provided.

**Comment by ObiSandwich** [comment]
Sounds good... If this is just a source issue, then not sure "corrupt files" is correct term any more. But so far I have only spotted two source formats, let's just hope they don't add any more.

**Comment by AustinHunting** [comment]
Please note, this project has been archived and all future updates will be posted to [team-hunting/ComicDownloader](https://github.com/team-hunting/ComicDownloader)

If you feel this issue has not been addressed to your satisfaction please open an issue or pull request in the new repository. As always we appreciate your support.
