### ISSUE TITLE
Final CBZ file size 

### ISSUE THREAD

**Issue by AustinHunting** [TravisHunting/ComicDownloader#23]
when we download the comics at low resolution the enc file size is reasonable, at full resolution the CBZ's get way to big way to fast.

Some general thoughts on this, we can try increasing the compression of the zip files (not sure if that will break cbz readers though) or we could convert the images into something lossless that compresses better (also would have to be able to render in a standard cbz reader) 

These are just food for though, not sure if it's worth the effort of adding and testing, or if we're okay with letting people just have larger CBZ files. 

Feel free to comment with thoughts or ideas

**Comment by ObiSandwich** [comment]
My feedback for you is the auto cbz is handy for the small runs, but I don't use it when a run includes TPB's or Annual's, as I remove them and recreate the cbz with just the main comic run.

Also, the comic reader I use chugs with too many pages, so I batch up the long runs into 20 comics per cbz.

Maybe an additional option for the user to disable the auto cbz when needed?

**Comment by TravisHunting** [comment]
We can add a -z flag to enable or disable zipping

**Comment by AustinHunting** [comment]
we can also add the option to produce CBT's (for no file compression at all) or CB7's (for way more compression control)

**Comment by AustinHunting** [comment]
@ObiSandwich can you elaborate on `Also, the comic reader I use chugs with too many pages, so I batch up the long runs into 20 comics per cbz.` a little more? 

Do you mean the reader slows down if there are too many images in a CBZ file? 
And when you say batch the long runs do you mean you unzip 20 comics, add all the images together, and rezip it into a single massive CBZ? 

I'm just trying to wrap my head around the use case here

**Comment by ObiSandwich** [comment]
> Do you mean the reader slows down if there are too many images in a CBZ file?

Yes. Also using a free cloud service with limited space to transfer from my PC, so the smaller file size helps too. And I'm limited to Fdroid apps, using an older (de-Googled) device, so there may be better apps (and devices) out there that can handle larger files.

> And when you say batch the long runs do you mean you unzip 20 comics, add all the images together, and rezip it into a single massive CBZ?

No. 20 comics per CBZ. Eg. 1-19, 20-39, 40-59 etc.

> {Insert your next potential question here}: Why do you use HiRes downloads?

Future proofing and easier on the eye :)

---
I'm not a CBZ expert. I'm an old school (paper) comic book dude and ex-Comixology user, so I'm kinda new to the world of CBZ - I'm picking this up as i go along and experimenting with this new format.

Thanka to you guys and readcomiconline.li I'm also looking into a future project of jail breaking an old iPad. If it all works out, I might have more app options to test then.

This script is already very versatile, so builiding on this with more arguments will suit a users personal preferences and situation.

**Comment by AustinHunting** [comment]
Please note, this project has been archived and all future updates will be posted to [team-hunting/ComicDownloader](https://github.com/team-hunting/ComicDownloader)

If you feel this issue has not been addressed to your satisfaction please open an issue or pull request in the new repository. As always we appreciate your support.
