### ISSUE TITLE
Using selenium for image grabbing 

### ISSUE THREAD

**Issue by AustinHunting** [TravisHunting/ComicDownloader#24]
What are your thoughts on moving away from requests and more into selenium for grabbing the images? it would run closed to a standard `chrome save as` and then we'd just have to filter the files like in the bash script 

Just food for thought, feel free to ping me with any ideas

**Comment by TravisHunting** [comment]
I think the image names all follow a certain format, "RC0002.JPG" for
example, so we could use selenium to scrape only the images that follow
that constraint

Might be more consistent and get rid if the 'corrupt' jpg thing

**Comment by AustinHunting** [comment]
I'm down to give that a go
