### ISSUE TITLE
Help guide?

### ISSUE THREAD

**Issue by ObiSandwich** [TravisHunting/ComicDownloader#3]
Hi... Hope you can help - I have made comicScraper.py Executable, but when I try to run this, nothing seems to happen and I only get the following output...

> $ ./comicScraper.py
Script for downloading CBZ files from readcomiconline.li
Usage: comicScraper.py <url> <comicTitle>
Arguments:
url: comicScraper.py https://readcomiconline.li/Comic/Star-Wars-2015/Issue-1?id=11921
comicTitle: ./DOWNLOADS
                (same as path of script execution)
Example: comicScraper.py https://readcomiconline.li/Comic/Lucifer-2016 Lucifer

These are my edits to the comicScraper.py file...

> def usage():
    print("Script for downloading CBZ files from readcomiconline.li")
    print("")
    print("Usage: comicScraper.py <url> <comicTitle>")
    print("")
    print("Arguments:")
    print("  - url: comicScraper.py https://readcomiconline.li/Comic/Star-Wars-2015/Issue-1?id=11921")
    print("  - comicTitle: ./DOWNLOADS")
    print("                (same as path of script execution)")
    print("")
    print("Example: comicScraper.py https://readcomiconline.li/Comic/Lucifer-2016 Lucifer")`

Is this correct?

MY SPEC: Linux LMDE4

**Comment by TravisHunting** [comment]
Hi there, i am glad you have found my script!

When running from the command line, you need to pass in the URL like so


"comicScraper.py
https://readcomiconline.li/Comic/Star-Wars-2015/Issue-1?id=11921 StarWars"

Argument 2 is the URL
Argument 3 is the name of a folder which will be created to store the
images

This script has been tested on Linux and windows so it should work

**Comment by TravisHunting** [comment]
Here is a previous version of the script which didn't use command line
arguments

https://github.com/TravisHunting/ComicDownloader/commit/d7901b252bfa3294a4f40744f95ee84cbe8d23f7


In order to make this run you will need to edit the variables at the top:

startUrl
comicTitle

path :

This version of the script was designed for windows so the  double
backslashes will need to be changed to single forward slashes

**Comment by ObiSandwich** [comment]
Thanks for your reply and thank you for your time - so I did have a look at the previous version but couldn't get that to work. So I ran the command from the Terminal below, but again nothing happened just the same message...

> $ ./comicScraper.py https://readcomiconline.li/Comic/Star-Wars-2015/Issue-1?id=11921
Script for downloading CBZ files from readcomiconline.li
Usage: comicScraper.py <url> <comicTitle>
Arguments:
   url: comicScraper.py https://readcomiconline.li/Comic/Star-Wars-2015/Issue-1?id=11921
   comicTitle: ./DOWNLOADS
                (same as path of script execution)
Example: comicScraper.py https://readcomiconline.li/Comic/Lucifer-2016 Lucifer

What exactly should I be writing in the Terminal please?

**Comment by TravisHunting** [comment]
With the base script, unedited, you should be able to run this in your
terminal:

"comicScraper.py
https://readcomiconline.li/Comic/Star-Wars-2015/Issue-1?id=11921 StarWars"

**Comment by ObiSandwich** [comment]
I just ran it using a fresh copy of comicScraper.py, but same thing happened...

> $ ./comicScraper.py https://readcomiconline.li/Comic/Star-Wars-2015/Issue-1?id=11921
Script for downloading CBZ files from readcomiconline.li
Usage: comicScraper.py <url> <comicTitle>
Arguments:
   url: The url of the comic you want to download
   comicTitle: The folder location to save the CBZ file to
                (same as path of script execution)
Example: comicScraper.py https://readcomiconline.li/Comic/Lucifer-2016 Lucifer

I tried the same command as Sudo as well, but that didn't help :(

Not sure if it helps, but just ran command 'python -V' and got: Python 2.7.16

Is this compatible? But for the script to run in the first place, then something is working right?

**Comment by TravisHunting** [comment]
It looks like you are missing the second argument, in this case the word
"StarWars"

Try

./comicScraper.py
https://readcomiconline.li/Comic/Star-Wars-2015/Issue-1?id=11921 StarWars

**Comment by ObiSandwich** [comment]
Ok that worked! Thank you... but folder contains extra blank JPG's  (0, 35-105) see attached. Is this script capable of converting these files into CBZ files?

> $ ./comicScraper.py https://readcomiconline.li/Comic/Star-Wars-2015/Issue-1?id=11921 StarWars
Starting to scrape StarWars from https://readcomiconline.li/Comic/Star-Wars-2015/Issue-1?id=11921
Issues:
['/Comic/Star-Wars-2015', '/Comic/Star-Wars-2015/Annual-4?id=134683', '/Comic/Star-Wars-2015/Issue-2?id=11926', '/Comic/Star-Wars-2015/Issue-1?id=11921&quality=lq', '/Comic/Star-Wars-2015/Issue-1?id=11921&quality=hq']
Issue Links:
['https://readcomiconline.li/Comic/Star-Wars-2015&readType=1', 'https://readcomiconline.li/Comic/Star-Wars-2015/Annual-4?id=134683&readType=1', 'https://readcomiconline.li/Comic/Star-Wars-2015/Issue-2?id=11926&readType=1', 'https://readcomiconline.li/Comic/Star-Wars-2015/Issue-1?id=11921&quality=lq&readType=1', 'https://readcomiconline.li/Comic/Star-Wars-2015/Issue-1?id=11921&quality=hq&readType=1']
Image Links:
[]
['https://2.bp.blogspot.com/-nF1-4y5jIIg/VouNOH08yUI/AAAAAAAAA2U/m1xlatfVfHU/s1600', 'https://2.bp.blogspot.com/RJKZHGbzbS39am0UmDLJ-y_iN9NcJWmMHUwNMrz2kt4jco3VL7sIYXyZS4FTp7UO8TohF2VDCfwclZvDKpDpbSg5nAy-iw9mSnPL5--vEc2HmlvVBCi0R6Zl6tbrRJpQdANPoD2L9w=s1600', 'https://2.bp.blogspot.com/wB2wUAOu839I1oeTZoQ9WQzUISwhltNagtvTPp1awQji_ndg2A8jFpko18s4FN5ecnI7_HcawW_Sz7Mb6FJuIYr5Zms3ipkO7HRIohJ2LFo5GURMHWi9mNsIo8kyYcEPmLE1Os5_WA=s1600', 'https://2.bp.blogspot.com/QG1zEfFJhT33Tg5EnGZ4P8Qhed0sEgvs2ccq3M9gfU6mmKzyCLl6jk7EA-Dup6ND6UvcGhWeARxmDqExovrachxt4Fl6lqG-dMdyUjjEPwvsLvzADrLXsBRd5CQq8SsGImAyLY99ZQ=s1600', 'https://2.bp.blogspot.com/arPduG2N6fLZGiWYPrpSZD3WBMRajk65lomIzZQeX2HkrQA7VMYHHnCVNKKmX-w0oJmxm3jj7zloOK7-8e6NFkywPHUOJ1WNruuPofPGwWM1r2xc858iVZST6ozb5cX76PjJJVQJ4A=s1600', 'https://2.bp.blogspot.com/1bU9v-Db07utikHFK7mVUgN6-7vmoXc8HR52SJU63tOOIptavZ089ci6KEUwTh6H4eleeTAhLZd5qYafSeQkL_yc_V8thzgiMFZa44BPrT1gWde-Q_I2S_g410AQfrJ7t9yb29ZTeQ=s1600', 'https://2.bp.blogspot.com/jx4zP4QhEfrums2EawTRWdy2DLbzlg9_w5E0cRIp_suvgmM1K3BdCeBuepbMfxwuc0D8IZbdQJHV9UlcJkqVGHRuu9XpzmrKBwf-vvP2_1yicEMhA1W0LY2cc1cppgw57XTVFuqmaQ=s1600', 'https://2.bp.blogspot.com/fuhopVbx4dbXFJWTgncbZ-pdGjsUOHbIT8mYRmYhR7UKdUbup6j4rKpsgG-6iBiMmGBhUPPBOJxsfMjRuKsTI3yx-lhJccf0tlvKF1Z2glwa03yS03dVTrR0RQmsPYczX6NeNOMSag=s1600', 'https://2.bp.blogspot.com/BmoeWE-0tO-dv5pJwB2dARZfnGBGyzPxHY73cbHM7Ys8YFxs5NGBinXzyzuIiqDVDreDiB4PmYVsrpaelusf4Uvxvl6GGONb2tFMjtMkPv3UhGLiWtQXfuQ7EN_hhAh9l-Xgq2RX8Q=s1600', 'https://2.bp.blogspot.com/KH8DrUTm3vrs350DYvRiG08svGjRIHmbQSHva71trUA8x0THdOntXRZcxo1l6iz0ODl_SvohcpO8HPRM2o5WVCFuZUxb5QMYpjcEwcZAoJEf0ZWLltOAFmbnofTclM3rQkUHfV94Fg=s1600', 'https://2.bp.blogspot.com/rGxtTjzS_qnvCeakXHxSGjUHVumC3l_gMcP8u5yQPx9wcmho81QRX3ZD4i4f19CiNCJl22GuBj0iKRSfKbBaDqDj6LGVjM0mhx7s1-ycc28WBJWsC_scr_pBN9fAlj0bkolsQ9vZGQ=s1600', 'https://2.bp.blogspot.com/g_bfhnGHat3N6HRxfWUkGreNi5U80RPEdEeRYUZqHtfZZiXlgoQPcVIOi8jPG9NbPwqG57WMBDg5-xmLhQVPIU6Dvsp9q17WLUy44KDnrI1wwZPVIAYAchWgxN_KylFTktJYaJexDg=s1600', 'https://2.bp.blogspot.com/k4oIZhbF8rNZrV9Uor3mRrtEvQQAjOr9n7FRjVfWQaLgv2FwSh_u3EqY5s04aY2wjvtwCrPdbmDCjVimN0-dgFISPviNsIztbngOWB9Cu-HG9s-0-gsQuPjbtAPp27h8teTkREXuQQ=s1600', 'https://2.bp.blogspot.com/4h6EvWf_hXAkfVIaxBtdzrtTMLk9xTLieNuPbNX_MiJgi9LVCO3O7lOavo3DJkROyu6SPltgLnw3bDkiGuF3eWJ6q1mwwhuy4uZOkKDaMlZ3yrkmGwB5WPWJQl2FljwKuHa5f-AFNA=s1600', 'https://2.bp.blogspot.com/2c7m8btTMv9qpSIEMyhvlva0CnPcam9KQeAejPqhYLqj74wmuVIcr3A5B5Vs3pgqFw6vvzwJ-WDmyB2W8gW3MalUzJy9TooKGrHi6XNpucpnTGFIC3yQOyuxvcMRYR5TFDe6vawlRQ=s1600', 'https://2.bp.blogspot.com/CqUaRxGu5jJreHQKb4WoPSlYhj0H2FaMKY0NtnV6ZJL3ShP4-pYwPWCUsD0Uku7VZpEb2nECXYrThK3ZgdJFUAFBsFzbtZMoVtkmOMFSCvxyd1-PjHWlXaowVJdjN1cayXuhlsv-5w=s1600', 'https://2.bp.blogspot.com/3Zmehks-nYvMFNiYcHPPwNi8hFWsDI_uR2r7NIaKAi-m52O1pM8dT7HkquPl3ubeswY1jTWpzfEjUWdhExUYGfKdx8ea_y-ZnyzB0c5qyQ9YRbOMvrTG214Q0jKiEuzpjJwN0czXbA=s1600', 'https://2.bp.blogspot.com/SxC_K3j2l_3_dfMmWBfPy1WCQmyM5iB3NGlhX5OqvjqEG5wnobrewn4T4tPDxPtR-EbpozrBagH-k5x5xsGp0MaCC2ElP6ANAZDwn9_9epZseSy0Hq_TMOU8ubWYAaiQoU7hlsV3Dw=s1600', 'https://2.bp.blogspot.com/96cNVufc0balxptlDVe--IeCAWwJn4ctfk_0xjjGGYcEcJgCWBHAsVUn08w_4MjGgTKPlSk_gDJQ2_bw1dvECKeDKFw8_Sjx40gmonUpFy7NBi9gw0TGEO645XRe33NME2-gBxkJRw=s1600', 'https://2.bp.blogspot.com/bQ9cNfyKTG6G1AJkh8nADPv4lwvcmEMDoXDQ4mM_hsc0EVOZ_q6450P4C_oEcBT4FWUiPBf5OfJ8NOvVZwwrEJ7APPVHCQnrh_HEJGPaRflhfkXPH6RK72tT7Q75E_rlvwx6-TNGgg=s1600', 'https://2.bp.blogspot.com/P_jY4EJzuY0Z8SwDgfu5BjVTQnxDqCz78CenC-sQc0GYt8meo48m3EAXYk2eE8ZFD29akNdIzDVhKgX8krimIlgHk-3jCylh8rlYmckpmW3OUWTHn9grhpqnaS8d-mlcXkHwBbtqJQ=s1600', 'https://2.bp.blogspot.com/GLL5Wi-e00mFq4P0IuxN3qRbaVRAzpMDBLfUsA0oBNbaQ0NeSGp3Eb_MPTnDkp5gzBrD1Iudc5JBLKgqtUm1kuytOXy9S2RvosYWqOJtlg5X0T6rbHDiQ3M_4WtLGqKyHYQaQ-T-qw=s1600', 'https://2.bp.blogspot.com/K4e4t4qGLJKQlRNUaO2VTitQ-u_MlWrB4AkaxjqmCHTJKBaV-4CvKm9nyXAUGvIpdZcUhg9fRvXcdD1i-Y2QoN8BFIDZ3_YWPHrlPZ3aiJzkTBSGZ6uSy3d9Y7lnGySsKgBIum4-Qg=s1600', 'https://2.bp.blogspot.com/VU1uc6YVRKUfhGk1vdC2qAC9lEJQkc8SsoJCmO_mVfVVxgwIKuHzhTFC-itfK7xKGBtw4NkaMxh-uIcSvJDcT6C0BEK2m3Mvj8Igs_s-kKia-G4XpnG8xy0IjfnvYMQ0TOqA3R2yTw=s1600', 'https://2.bp.blogspot.com/Ib9IRVp8BAgQ71ni2KJCITty4ndsRXPin4wHVSnSXU_kxzWYwfnEYO_lolMLgi3TW_ISJYxiUnYk2YlVBpKjqR_nA_q3OPu88XLEofhvxffGH_f28-0k5FjGVI1C3mLOmRdDao9Prg=s1600', 'https://2.bp.blogspot.com/X7EHmmBGrAPqwBaMBotwfxXbE2nqELcc-4InCMR1nTccpFIiWCX-jFjU-XnAtyVhW5SUF9AtjuIRTtcGLy-fsSnNQRj-DJdc29Bt-qbIcZJdCvfl94YZ1zVHQZO57FP0lg9sz_FcbQ=s1600', 'https://2.bp.blogspot.com/E3OvcWY1_aCZpON25oroKYBHwHnDBRQfxGUgomzPMj-GmO-yOVDfbPJAEM0EUuootPiFHt9a3UbkKVWkyHQUhMl4PezgpxkrPWCAubU1-a3DpG-2g9_xHrPFcJX8hx2vgZZFu5hbxw=s1600', 'https://2.bp.blogspot.com/XwzADtTZDAjMearlyZoWDcDeAyU7P-LWqW7SOgN6eITIxJgWgVAue8Jn-C0zUeO4gz1rmHqYXjPCEJfK-mzBsLwwmD_RcV0sddePHkpPahjcnprwyPUg_4Pzi_mf1FPdXhj5WQxYiA=s1600', 'https://2.bp.blogspot.com/2eBm-5YHZ6-6vdbLjNveYvHhWl9tTdO_l4-kJMysaxgQvncSbtSfTrz8nNApvJVj1FT56J17lL3Zf0O1JmP0iIbxn8ndIk1PzpFnGHpdiyMdiGPhrl6-rIVUI8unKnnq1nUgNOe_MQ=s1600', 'https://2.bp.blogspot.com/NrOC-Z7u7qSsylsSFeuoWsBk5nCUIBKgeTOmvdeCeq-aqkwY8RUUu4OwqWeE0ZRa6Tsaz3zsgwpF5_RVcVwo6KsovwhLetfKxtPgRn6jmscATeNpvgjIaoyMN_ZYiOI8vxx3hfe9Tw=s1600', 'https://2.bp.blogspot.com/z52wuHZrNMgV8Di6RiBU7Oc_qspTDK98_IW2yOIKsT-I38pne_G6zulQygjwYqcmA8m-LLUTeesmExYtC71M2p1XZ8KhPH9J_-RHR9WqKy0YJF06xFQvpay3k7QjZoBzMFmY3UuipQ=s1600', 'https://2.bp.blogspot.com/pRtRGD6WKJboIdn7HzSpTAWsVuo9rbeVt41b-OAisH8D6hh2df0txn632-nY5IO9CCxltu7b8h-f2q2XdoyqsT0FTAxqfa1Pzz9rycVMPfdJ8Wo41w4kPVVgyLtUnys_3xlaXCtbmw=s1600', 'https://2.bp.blogspot.com/uESrHYEBTU2j-2tdlrIssorBpMNfPv5MSPK2BGbZf9JFB2_WcHfYdLXrT8GqpE4a9Y2hDM3exTnhOQwfEe-6PoGkrp_-uvLFGP32qB46XNVwnMcXnqxub42uryDtGAanrkgn6oT51A=s1600', 'https://2.bp.blogspot.com/skKuVESyWOTj8zCqq9E4CEYp05U73qv9vHY4xXmRzJdiN5WblfOKKy5N6NsL3b0ReasOe9D8qCmtorpaxIQ_qV5QaTWm3Hu-ONjjBsOn_fjSN0EpLmJd43_Z2ytyx0PR7qqwI__WNg=s1600', 'https://2.bp.blogspot.com/X2wjj5zqQFG8yC0Pxo_L8m6IuBm6lUduLfMeyny5zoAhR4Pp2rya4KKyVIjZPHPkBRyF_LxiKCdU3t-Kv4hj7jcYnIDXuct4n_nm0lBCYxX8H4isWkMjUcqNKsPj06Gqn3GIQEyA0w=s1600']
['https://2.bp.blogspot.com/-nF1-4y5jIIg/VouNOH08yUI/AAAAAAAAA2U/m1xlatfVfHU/s1600', 'https://2.bp.blogspot.com/-XA6a_i6XHMU/VouPtNEX2zI/AAAAAAAAeN0/5XpdQ4o4G6s/s1600', 'https://2.bp.blogspot.com/-UVGrpUthaM4/VouPtWqGdwI/AAAAAAAAeN0/qT8NuVq2pys/s1600', 'https://2.bp.blogspot.com/-97xSpBHj_iA/VouPteVxkbI/AAAAAAAAeN0/iJZhqAfsmkk/s1600', 'https://2.bp.blogspot.com/-a6don_9nS8k/VouPt33tpdI/AAAAAAAAeN0/G_MN0b8x3tE/s1600', 'https://2.bp.blogspot.com/-T_Lk2NBSays/VouPtw9ZpeI/AAAAAAAAeN0/E-7JVwW2P2w/s1600', 'https://2.bp.blogspot.com/-RF3tPm5pZlM/VouPuAdRhnI/AAAAAAAAeN0/tD82AXql0q8/s1600', 'https://2.bp.blogspot.com/-h1sqotkOkc8/VouPuhfOyGI/AAAAAAAAeN0/TShxWzZjBQ8/s1600', 'https://2.bp.blogspot.com/-VNfr-EAPuBU/VouPvPOKBhI/AAAAAAAAeN0/OcndKmK2spE/s1600', 'https://2.bp.blogspot.com/-0kjObi9J31k/VouPvEwYysI/AAAAAAAAeN0/PduN1gjsaeY/s1600', 'https://2.bp.blogspot.com/-RZ3ZLAkbaas/VouPvU-IzBI/AAAAAAAAeN0/En-Z6XG-ULM/s1600', 'https://2.bp.blogspot.com/-RIIqBlPH7fk/VouPv0Yrz6I/AAAAAAAAeN0/-6jp34ySSLU/s1600', 'https://2.bp.blogspot.com/-Q2ctGfuwSus/VouPvwvobZI/AAAAAAAAeN0/DiX3l1Un1zY/s1600', 'https://2.bp.blogspot.com/-O1XeU5L-o1A/VouPwaDvg5I/AAAAAAAAeOA/gCn1pDH2zEE/s1600', 'https://2.bp.blogspot.com/-Cufzq96gaZg/VouPwlNr-QI/AAAAAAAAeN0/LtTzuv4nTTw/s1600', 'https://2.bp.blogspot.com/-9m9ZP7ezSqg/VouPwhEyGFI/AAAAAAAAeN0/YTg9HOtUx48/s1600', 'https://2.bp.blogspot.com/-JCgJYJgtmQ8/VouPxH1KglI/AAAAAAAAeN0/gXVG6pzWeXQ/s1600', 'https://2.bp.blogspot.com/-jmOdz-gvzCk/VouPxIFwCII/AAAAAAAAeN0/fNddd3NNRmM/s1600', 'https://2.bp.blogspot.com/-Jrn6d2v3LPk/VouPxWz8slI/AAAAAAAAeN0/lnScgiIuzBk/s1600', 'https://2.bp.blogspot.com/-qUHqbJKzMdw/VouPyGtviDI/AAAAAAAAeN0/6MnO9omFeQc/s1600', 'https://2.bp.blogspot.com/-VkSYK1Xt3JQ/VouPyYWwIhI/AAAAAAAAeN8/YrHvcXZuvI8/s1600', 'https://2.bp.blogspot.com/-S3SZyDH7bx0/VouPycVjCtI/AAAAAAAAeN0/RGmTDv1FIcM/s1600', 'https://2.bp.blogspot.com/-YAI1qq-vWCY/VouPzJro8xI/AAAAAAAAeN0/rTBGjgbmxYk/s1600', 'https://2.bp.blogspot.com/--4acuZecq0M/VouPzMMKoYI/AAAAAAAAeN0/hrJgO4xHQis/s1600']
['https://2.bp.blogspot.com/-nF1-4y5jIIg/VouNOH08yUI/AAAAAAAAA2U/m1xlatfVfHU/s1600', 'https://2.bp.blogspot.com/-zpVz_2DFEAI/VouOhIcBOmI/AAAAAAAAd-A/EzKSlM_qpHk/s1600', 'https://2.bp.blogspot.com/-QCUqI4D0uE8/VouOhLhbhjI/AAAAAAAAd-A/D0TcpXaql4c/s1600', 'https://2.bp.blogspot.com/-eTv_yfNGNZ8/VouOhEetr9I/AAAAAAAAd-A/odcsVh17ODE/s1600', 'https://2.bp.blogspot.com/-y4JztoFCO8E/VouOhV12RGI/AAAAAAAAd-A/Ibjpcq3aJII/s1600', 'https://2.bp.blogspot.com/-Ay_Y-hKvyC4/VouOh_cPflI/AAAAAAAAd-A/tRp_-UZtz_E/s1600', 'https://2.bp.blogspot.com/-cv96xMHfD-o/VouOh3BYsnI/AAAAAAAAd-A/GP4XEQMH2To/s1600', 'https://2.bp.blogspot.com/-hzUf7Ckh0t8/VouOiLDf5CI/AAAAAAAAd-A/7tHfI84ecR4/s1600', 'https://2.bp.blogspot.com/-_l25t_tU6qo/VouOidKPMbI/AAAAAAAAd-A/ji9r24iicNI/s1600', 'https://2.bp.blogspot.com/-lguFcwhNnR4/VouOiZvJiaI/AAAAAAAAd-A/HgsXyreHey8/s1600', 'https://2.bp.blogspot.com/-n5dBX2Aspk8/VouOiqhvCMI/AAAAAAAAd-A/qhWViLNNgSQ/s1600', 'https://2.bp.blogspot.com/-t0IkTI48_d4/VouOjjMc3lI/AAAAAAAAd-A/o1-14GFhEHY/s1600', 'https://2.bp.blogspot.com/-4fbFKyHBEOE/VouOjoPw_CI/AAAAAAAAd-A/-cmjniq96LI/s1600', 'https://2.bp.blogspot.com/-vC3tsjH1JI4/VouOj1iEskI/AAAAAAAAd-A/QdtJajYtiic/s1600', 'https://2.bp.blogspot.com/-8UfdpgNaUXo/VouOkmSIEGI/AAAAAAAAd-A/a63DHxGf62w/s1600', 'https://2.bp.blogspot.com/-NtOnnQ-HeUo/VouOku4K7nI/AAAAAAAAd-A/F_q5nP4pctA/s1600', 'https://2.bp.blogspot.com/-ghlNUNTCzWc/VouOkw8XUMI/AAAAAAAAd-A/BcnBaNNA9So/s1600', 'https://2.bp.blogspot.com/-nsdj4mb4djY/VouOlaLny7I/AAAAAAAAd-A/BOpcfU3laFQ/s1600', 'https://2.bp.blogspot.com/-KMrwaxYqJnw/VouOlU4ZXEI/AAAAAAAAd-A/bp76Hr54QKE/s1600', 'https://2.bp.blogspot.com/-hJLR_CWiUKU/VouOl8k0fiI/AAAAAAAAd-A/IfLg2rRzIWU/s1600', 'https://2.bp.blogspot.com/-b8gj-NgDI1s/VouOl5kq9YI/AAAAAAAAd-A/HVymYERl9Kc/s1600', 'https://2.bp.blogspot.com/-Eax_jXxkmGc/VouOmPreupI/AAAAAAAAd-A/-2dXsRtuQyk/s1600', 'https://2.bp.blogspot.com/-EVI7RA1rVA0/VouOmiBa_-I/AAAAAAAAd-A/hHM4kwP3waw/s1600', 'https://2.bp.blogspot.com/-uCJnrR-pJNI/VouOm9hlgWI/AAAAAAAAd-A/ntXZWwEsLSA/s1600', 'https://2.bp.blogspot.com/-VK9w5PMvReA/VouOnKvrSRI/AAAAAAAAd-A/XEFMFRIMnaI/s1600', 'https://2.bp.blogspot.com/-7EaRvGW41Zg/VouOnofK4VI/AAAAAAAAd-A/dhpTCejMF10/s1600', 'https://2.bp.blogspot.com/-gtdBKpGG0U8/VouOnzRAJPI/AAAAAAAAd-A/4o6fWOgmAXI/s1600', 'https://2.bp.blogspot.com/-rGh1s3Z2bFo/VouOoMVlIBI/AAAAAAAAd-A/f5QDM5nG5mQ/s1600', 'https://2.bp.blogspot.com/-IbawArWgmDw/VouOocdy2MI/AAAAAAAAd-A/g6MoFcEDjVw/s1600', 'https://2.bp.blogspot.com/-MKNrMPmZejs/VouOoVVIfsI/AAAAAAAAd-M/x6KDVa-RvI4/s1600', 'https://2.bp.blogspot.com/-SH_o3xd2SRE/VouOoxb-WgI/AAAAAAAAd-Q/t_DaKc7w8IE/s1600', 'https://2.bp.blogspot.com/-XNEVOEZsEnU/VouOo-NkP7I/AAAAAAAAd-A/6Zt-UM8o_pE/s1600', 'https://2.bp.blogspot.com/-HXYeEuLDaYw/VouOpeSxp5I/AAAAAAAAd-A/RJdRX2pwD0M/s1600', 'https://2.bp.blogspot.com/-CIfK6yXWebs/VouOpns8cLI/AAAAAAAAd-U/KjPNSN7hQCQ/s1600', 'https://2.bp.blogspot.com/-gcM66TderwE/VouOpuQ96EI/AAAAAAAAd-A/FMZz-2yp1XU/s1600', 'https://2.bp.blogspot.com/-EZyTXe-H5fw/VouOqAeMsUI/AAAAAAAAd-A/8di7wkWvnPE/s1600', 'https://2.bp.blogspot.com/-eYXAmGGOu6k/VouOqc416UI/AAAAAAAAd-A/Egg4fF73WrQ/s1600', 'https://2.bp.blogspot.com/-3_kA-Z3aiWo/VouOqsO_rSI/AAAAAAAAd-A/V901zfvna7k/s1600', 'https://2.bp.blogspot.com/-sZi_ajxv8MY/VouOq9MS7-I/AAAAAAAAd-A/jw8Nw0D3iNo/s1600', 'https://2.bp.blogspot.com/-gXAPfnRyROA/VouOrXpFEDI/AAAAAAAAd-A/oTsB662nuRE/s1600', 'https://2.bp.blogspot.com/-HqYyDxe4O9I/VouOrgZ5mZI/AAAAAAAAd-A/bndJPHXEGMg/s1600', 'https://2.bp.blogspot.com/-XRtgmXYQ0V0/VouOrjDxS0I/AAAAAAAAd-I/QAwPaTx9xh4/s1600', 'https://2.bp.blogspot.com/-plD-74gXtEY/VouOsPN93MI/AAAAAAAAd-A/cWwXUDt7_6w/s1600', 'https://2.bp.blogspot.com/-UrNN6WOc9Os/VouOsQ2rZWI/AAAAAAAAd-A/vhoa4ayoA8M/s1600', 'https://2.bp.blogspot.com/-G1n2BvFx4Z4/VouOs_asEnI/AAAAAAAAd-A/IlZtOwY5_y0/s1600']
['https://2.bp.blogspot.com/-nF1-4y5jIIg/VouNOH08yUI/AAAAAAAAA2U/m1xlatfVfHU/s1600', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
Traceback (most recent call last):
  File "./comicScraper.py", line 146, in <module>
    main()
  File "./comicScraper.py", line 119, in main
    saveImagesFromImageLinks(issue)
  File "./comicScraper.py", line 77, in saveImagesFromImageLinks
    saveImageFromUrl(imageLink)
  File "./comicScraper.py", line 91, in saveImageFromUrl
    f.write(requests.get(url).content)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
![Screenshot from 2022-01-01 22-03-15](https://user-images.githubusercontent.com/41534480/147861076-ccb76529-a55d-429a-a028-89289d3f67d4.png)

**Comment by TravisHunting** [comment]
Ah, yes I see what happened. You need to use the base url that contains
links to all the issues.

This is the command you want to run, sorry for the confusion

 ./comicScraper.py  https://readcomiconline.li/Comic/Star-Wars-2015 StarWars

(The URL used is slightly different)

**Comment by TravisHunting** [comment]
To answer your other question, no this script does not create the CBZ file
for you, that is on the todo list. Please feel free to add that feature and
submit a pull request 😊

**Comment by TravisHunting** [comment]
Please note that script may appear to hang when you run it on a comic with
lots of issues. It is running, but it has to go slowly so that the website
doesn't make us do a captcha.

**Comment by ObiSandwich** [comment]
Thanks again, that kinda worked, but missed some issues with the same empty 1.6kb JPG's like my previous screenshot - missed the Annuals and 1-13, 15-16. Is there any reason why it does this?

**Comment by ObiSandwich** [comment]
...so I tested this with a smaller comic run and it worked really well, with no skips or zombie JPG's.

`./comicScraper.py https://readcomiconline.li/Comic/Punisher-MAX-The-Platoon PunisherMAXThePlatoon`

But tested same Star Wars link above and it didn't get every JPG again, this time different ones were missing, but still a large amount of the pages from the annuals and early issues. Is this script tripping up because of the size of this run?

TOTAL COMICS: 75 + 4 Annuals (2,069 JPG's)

`./comicScraper.py https://readcomiconline.li/Comic/Star-Wars-2015 StarWars2015`

**Comment by ObiSandwich** [comment]
Not sure if it helps, but here's my PC specs...

CPU: Intel(R) Core(TM) i7 CPU 860  @ 2.80GHz
RAM: 16GB
LINUX: LMDE4 (64bit)

**Comment by TravisHunting** [comment]
It's possible that the website is triggering its anti bot protection. On
our list of things to add in the immediate future is a check for when this
gets triggered

**Comment by ObiSandwich** [comment]
Yeah I thought so, I have been seeing some weird stuff after maybe 30-60 minutes the script doesn't create a folder or JPG's after use. Closing everything down and restarting sometimes fixes this. I guess my IP address is booted off their server for a period of time??

So... is there a way around this by reducing large batches to smaller batches? So is there an argument/option to download a particular run of issues, eg. 1 to 30, 31 to 75?

**Comment by ObiSandwich** [comment]
Thanks again for all your help. I only discovered ReadComicsOnline recently so I'm so glad to have discovered your script! I originally tried the Comic-DL script, but that didn't work out and I got a load of Python errors. So based on that experience with their script, please don't be tempted to over complicate yours and keep it simple... and working :)
