### ISSUE TITLE
ENHANCEMENT: Filename number format

### ISSUE THREAD

**Issue by ObiSandwich** [TravisHunting/ComicDownloader#8]
I use the Fdroid comic reader app 'Seeneva'. Which is quite sensitive to numbers unfortunately, which means if the filename numbering is not compatible, the comic pages are displayed in the wrong order in the app. So to fix this, after I have run your wonderful script, I have to use rename software to rename all downloaded JPG's to a 4 digit format, eg. 1 = 0001.

Is there any way you can output downloaded JPG's to include a 4 digit number format please?

**Comment by ObiSandwich** [comment]
...make that 5 digits! Just had a problem with renaming a large selection of comics in the rename software with 4 digits. Could the user choose the number of digits?

**Comment by TravisHunting** [comment]
Great suggestion, we've just added this feature a few hours ago now 😊

**Comment by TravisHunting** [comment]
We've updated it to automatically read the number of digits it needs out of the list of images based on length of the list

**Comment by ObiSandwich** [comment]
Cool. Thanks so much :)

**Comment by ObiSandwich** [comment]
Just tested your latest script this with...

`./comicScraper.py -u https://readcomiconline.li/Comic/Die -f Die`

And it didn't work with the app I use because the number of digits need to be increased. This comic numbering is ok from 00-09, but there are no proceeding 0's after that. So the app I use gets lost from 10 on-wards. So this comic needs a couple more 0's at the front :)

**Comment by AustinHunting** [comment]
It appears `Seeneva` supports the standard CBZ format. The single issue comic files produced conform to the CBZ standard (still working on complete issue). 
Theoretically there should be no need to prepadd zeros other than to ensure all images have the same file length.

Can you explain your issue in a little more depth, or provide a description of what happens on pages after 09 ?

Can you also verify that the issue still exists if you load a single issue comic i.e. `Die-Issue-4.cbz`

**Comment by TravisHunting** [comment]
I think he's referring to the this:

If the first issue has less than 100 images, the files will only prepad to 2 digits
but if the comic as a whole has over 100, then anything in the first issue must be prepended to 3 digits
same if the comic has over 1000, etc

So the issue is definitely valid if you're trying to read the "Complete" version of the download

I should have fixed that with this latest PR I've just submitted

**Comment by ObiSandwich** [comment]
Thanks again! That looks like it works :) Only tested this on a run of 3 digits (000-820jpg).
